import type { CSSProperties } from "react";
import {
  colorTokens,
  componentTokens,
  motionTokens,
  radiusTokens,
  shadowTokens,
  spacingTokens,
  type ThemeMode,
  typographyTokens,
  zIndexTokens
} from "../tokens";

export const themeVariables = (mode: ThemeMode): CSSProperties => ({
  "--sv-color-primary": colorTokens[mode].primary,
  "--sv-color-secondary": colorTokens[mode].secondary,
  "--sv-color-accent": colorTokens[mode].accent,
  "--sv-color-background": colorTokens[mode].background,
  "--sv-color-surface": colorTokens[mode].surface,
  "--sv-color-surface-raised": colorTokens[mode].surfaceRaised,
  "--sv-color-border": colorTokens[mode].border,
  "--sv-color-text": colorTokens[mode].text,
  "--sv-color-text-muted": colorTokens[mode].textMuted,
  "--sv-color-success": colorTokens[mode].success,
  "--sv-color-warning": colorTokens[mode].warning,
  "--sv-color-danger": colorTokens[mode].danger,
  "--sv-color-focus": colorTokens[mode].focus,
  "--sv-space-4": spacingTokens[4],
  "--sv-space-8": spacingTokens[8],
  "--sv-space-12": spacingTokens[12],
  "--sv-space-16": spacingTokens[16],
  "--sv-space-24": spacingTokens[24],
  "--sv-space-32": spacingTokens[32],
  "--sv-space-48": spacingTokens[48],
  "--sv-space-64": spacingTokens[64],
  "--sv-space-80": spacingTokens[80],
  "--sv-border-width": componentTokens.borderWidth,
  "--sv-control-height": componentTokens.controlHeight,
  "--sv-disabled-opacity": componentTokens.disabledOpacity,
  "--sv-tooltip-max": componentTokens.tooltipMaxWidth,
  "--sv-avatar-size": componentTokens.avatarSize,
  "--sv-spinner-size": componentTokens.spinnerSize,
  "--sv-skeleton-size": componentTokens.skeletonSize,
  "--sv-content-max": componentTokens.contentMaxWidth,
  "--sv-card-asset-height": componentTokens.cardAssetHeight,
  "--sv-hero-content-max": componentTokens.heroContentMaxWidth,
  "--sv-sidebar-min": componentTokens.sidebarMinWidth,
  "--sv-guide-reading-width": componentTokens.guideReadingWidth,
  "--sv-guide-toc-width": componentTokens.guideTocWidth,
  "--sv-radius-sm": radiusTokens.sm,
  "--sv-radius-md": radiusTokens.md,
  "--sv-radius-lg": radiusTokens.lg,
  "--sv-radius-pill": radiusTokens.pill,
  "--sv-shadow-sm": shadowTokens.sm,
  "--sv-shadow-md": shadowTokens.md,
  "--sv-shadow-focus": shadowTokens.focus,
  "--sv-motion-fast": motionTokens.fast,
  "--sv-motion-base": motionTokens.base,
  "--sv-motion-slow": motionTokens.slow,
  "--sv-motion-easing": motionTokens.easing,
  "--sv-font-display": typographyTokens.fontFamily.display,
  "--sv-font-body": typographyTokens.fontFamily.body,
  "--sv-font-code": typographyTokens.fontFamily.code,
  "--sv-font-caption-size": typographyTokens.caption.fontSize,
  "--sv-font-small-size": typographyTokens.small.fontSize,
  "--sv-font-h4-size": typographyTokens.h4.fontSize,
  "--sv-font-hero-size": typographyTokens.hero.fontSize,
  "--sv-font-hero-line-height": typographyTokens.hero.lineHeight,
  "--sv-font-section-size": typographyTokens.section.fontSize,
  "--sv-font-section-line-height": typographyTokens.section.lineHeight,
  "--sv-font-card-title-size": typographyTokens.cardTitle.fontSize,
  "--sv-font-card-title-line-height": typographyTokens.cardTitle.lineHeight,
  "--sv-font-body-line-height": typographyTokens.body.lineHeight,
  "--sv-z-base": zIndexTokens.base,
  "--sv-z-sticky": zIndexTokens.sticky,
  "--sv-z-dropdown": zIndexTokens.dropdown,
  "--sv-z-overlay": zIndexTokens.overlay,
  "--sv-z-modal": zIndexTokens.modal,
  "--sv-z-tooltip": zIndexTokens.tooltip
} as CSSProperties);
